#pragma once

#include "NativeGameplayTags.h"

namespace LBTags
{
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_1);
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_2);
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_3);
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_4);
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_5);
	LASTBELL_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Warden_Stage_6);
}
